static constexpr char limits_description_reply[] = R"({
  "datagram": [
    {
      "header": [
        {
          "specificationVersion": "1.3.0"
        },
        {
          "addressSource": [
            {
              "device": "d:_n:Demo_HEMS-123456789"
            },
            {
              "entity": [
                1
              ]
            },
            {
              "feature": 2
            }
          ]
        },
        {
          "addressDestination": [
            {
              "device": "d:_n:Demo_ControlBox-123456789"
            },
            {
              "entity": [
                1
              ]
            },
            {
              "feature": 2
            }
          ]
        },
        {
          "msgCounter": 11
        },
        {
          "msgCounterReference": 7
        },
        {
          "cmdClassifier": "reply"
        }
      ]
    },
    {
      "payload": [
        {
          "cmd": [
            [
              {
                "loadControlLimitDescriptionListData": [
                  {
                    "loadControlLimitDescriptionData": [
                      [
                        {
                          "limitId": 0
                        },
                        {
                          "limitType": "signDependentAbsValueLimit"
                        },
                        {
                          "limitCategory": "obligation"
                        },
                        {
                          "limitDirection": "consume"
                        },
                        {
                          "measurementId": 0
                        },
                        {
                          "unit": "W"
                        },
                        {
                          "scopeType": "activePowerLimit"
                        }
                      ],
                      [
                        {
                          "limitId": 1
                        },
                        {
                          "limitType": "signDependentAbsValueLimit"
                        },
                        {
                          "limitCategory": "obligation"
                        },
                        {
                          "limitDirection": "produce"
                        },
                        {
                          "measurementId": 0
                        },
                        {
                          "unit": "W"
                        },
                        {
                          "scopeType": "activePowerLimit"
                        }
                      ]
                    ]
                  }
                ]
              }
            ]
          ]
        }
      ]
    }
  ]
})";
