/*
 * Copyright 2025 NIBE AB
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * @file
 * @brief Websocket debug logging implementation
 */

#include "websocket_debug.h"

#if defined(WEBSOCKET_DEBUG) || defined(WEBSOCKET_SERVER_DEBUG)

#include <libwebsockets.h>

#include "src/common/array_util.h"

typedef struct LwsCbReasonMapping LwsCbReasonMapping;

struct LwsCbReasonMapping {
  enum lws_callback_reasons reason;
  const char* reason_txt;
};

#define LWS_CB_REASON_MAPPING(r) {LWS_CALLBACK_##r, "LWS_CALLBACK_" #r}

const char* WebsocketLwsReasonToString(enum lws_callback_reasons reason) {
  static const LwsCbReasonMapping lws_cb_reason_lut[] = {
      LWS_CB_REASON_MAPPING(PROTOCOL_INIT),
      LWS_CB_REASON_MAPPING(PROTOCOL_DESTROY),
      LWS_CB_REASON_MAPPING(WSI_CREATE),
      LWS_CB_REASON_MAPPING(WSI_DESTROY),
      LWS_CB_REASON_MAPPING(WSI_TX_CREDIT_GET),
      LWS_CB_REASON_MAPPING(OPENSSL_LOAD_EXTRA_CLIENT_VERIFY_CERTS),
      LWS_CB_REASON_MAPPING(OPENSSL_LOAD_EXTRA_SERVER_VERIFY_CERTS),
      LWS_CB_REASON_MAPPING(OPENSSL_PERFORM_CLIENT_CERT_VERIFICATION),
      LWS_CB_REASON_MAPPING(SSL_INFO),
      LWS_CB_REASON_MAPPING(OPENSSL_PERFORM_SERVER_CERT_VERIFICATION),
      LWS_CB_REASON_MAPPING(SERVER_NEW_CLIENT_INSTANTIATED),
      LWS_CB_REASON_MAPPING(HTTP),
      LWS_CB_REASON_MAPPING(HTTP_BODY),
      LWS_CB_REASON_MAPPING(HTTP_BODY_COMPLETION),
      LWS_CB_REASON_MAPPING(HTTP_FILE_COMPLETION),
      LWS_CB_REASON_MAPPING(HTTP_WRITEABLE),
      LWS_CB_REASON_MAPPING(CLOSED_HTTP),
      LWS_CB_REASON_MAPPING(FILTER_HTTP_CONNECTION),
      LWS_CB_REASON_MAPPING(ADD_HEADERS),
      LWS_CB_REASON_MAPPING(VERIFY_BASIC_AUTHORIZATION),
      LWS_CB_REASON_MAPPING(CHECK_ACCESS_RIGHTS),
      LWS_CB_REASON_MAPPING(PROCESS_HTML),
      LWS_CB_REASON_MAPPING(HTTP_BIND_PROTOCOL),
      LWS_CB_REASON_MAPPING(HTTP_DROP_PROTOCOL),
      LWS_CB_REASON_MAPPING(HTTP_CONFIRM_UPGRADE),
      LWS_CB_REASON_MAPPING(ESTABLISHED_CLIENT_HTTP),
      LWS_CB_REASON_MAPPING(CLOSED_CLIENT_HTTP),
      LWS_CB_REASON_MAPPING(RECEIVE_CLIENT_HTTP_READ),
      LWS_CB_REASON_MAPPING(RECEIVE_CLIENT_HTTP),
      LWS_CB_REASON_MAPPING(COMPLETED_CLIENT_HTTP),
      LWS_CB_REASON_MAPPING(CLIENT_HTTP_WRITEABLE),
      LWS_CB_REASON_MAPPING(CLIENT_HTTP_REDIRECT),
      LWS_CB_REASON_MAPPING(CLIENT_HTTP_BIND_PROTOCOL),
      LWS_CB_REASON_MAPPING(CLIENT_HTTP_DROP_PROTOCOL),
      LWS_CB_REASON_MAPPING(ESTABLISHED),
      LWS_CB_REASON_MAPPING(CLOSED),
      LWS_CB_REASON_MAPPING(SERVER_WRITEABLE),
      LWS_CB_REASON_MAPPING(RECEIVE),
      LWS_CB_REASON_MAPPING(RECEIVE_PONG),
      LWS_CB_REASON_MAPPING(WS_PEER_INITIATED_CLOSE),
      LWS_CB_REASON_MAPPING(FILTER_PROTOCOL_CONNECTION),
      LWS_CB_REASON_MAPPING(CONFIRM_EXTENSION_OKAY),
      LWS_CB_REASON_MAPPING(WS_SERVER_BIND_PROTOCOL),
      LWS_CB_REASON_MAPPING(WS_SERVER_DROP_PROTOCOL),
      LWS_CB_REASON_MAPPING(CLIENT_CONNECTION_ERROR),
      LWS_CB_REASON_MAPPING(CLIENT_FILTER_PRE_ESTABLISH),
      LWS_CB_REASON_MAPPING(CLIENT_ESTABLISHED),
      LWS_CB_REASON_MAPPING(CLIENT_CLOSED),
      LWS_CB_REASON_MAPPING(CLIENT_APPEND_HANDSHAKE_HEADER),
      LWS_CB_REASON_MAPPING(CLIENT_RECEIVE),
      LWS_CB_REASON_MAPPING(CLIENT_RECEIVE_PONG),
      LWS_CB_REASON_MAPPING(CLIENT_WRITEABLE),
      LWS_CB_REASON_MAPPING(CLIENT_CONFIRM_EXTENSION_SUPPORTED),
      LWS_CB_REASON_MAPPING(WS_EXT_DEFAULTS),
      LWS_CB_REASON_MAPPING(FILTER_NETWORK_CONNECTION),
      LWS_CB_REASON_MAPPING(WS_CLIENT_BIND_PROTOCOL),
      LWS_CB_REASON_MAPPING(WS_CLIENT_DROP_PROTOCOL),
      LWS_CB_REASON_MAPPING(GET_THREAD_ID),
      LWS_CB_REASON_MAPPING(ADD_POLL_FD),
      LWS_CB_REASON_MAPPING(DEL_POLL_FD),
      LWS_CB_REASON_MAPPING(CHANGE_MODE_POLL_FD),
      LWS_CB_REASON_MAPPING(LOCK_POLL),
      LWS_CB_REASON_MAPPING(UNLOCK_POLL),
      LWS_CB_REASON_MAPPING(CGI),
      LWS_CB_REASON_MAPPING(CGI_TERMINATED),
      LWS_CB_REASON_MAPPING(CGI_STDIN_DATA),
      LWS_CB_REASON_MAPPING(CGI_STDIN_COMPLETED),
      LWS_CB_REASON_MAPPING(CGI_PROCESS_ATTACH),
      LWS_CB_REASON_MAPPING(SESSION_INFO),
      LWS_CB_REASON_MAPPING(GS_EVENT),
      LWS_CB_REASON_MAPPING(HTTP_PMO),
      LWS_CB_REASON_MAPPING(RAW_PROXY_CLI_RX),
      LWS_CB_REASON_MAPPING(RAW_PROXY_SRV_RX),
      LWS_CB_REASON_MAPPING(RAW_PROXY_CLI_CLOSE),
      LWS_CB_REASON_MAPPING(RAW_PROXY_SRV_CLOSE),
      LWS_CB_REASON_MAPPING(RAW_PROXY_CLI_WRITEABLE),
      LWS_CB_REASON_MAPPING(RAW_PROXY_SRV_WRITEABLE),
      LWS_CB_REASON_MAPPING(RAW_PROXY_CLI_ADOPT),
      LWS_CB_REASON_MAPPING(RAW_PROXY_SRV_ADOPT),
      LWS_CB_REASON_MAPPING(RAW_PROXY_CLI_BIND_PROTOCOL),
      LWS_CB_REASON_MAPPING(RAW_PROXY_SRV_BIND_PROTOCOL),
      LWS_CB_REASON_MAPPING(RAW_PROXY_CLI_DROP_PROTOCOL),
      LWS_CB_REASON_MAPPING(RAW_PROXY_SRV_DROP_PROTOCOL),
      LWS_CB_REASON_MAPPING(RAW_RX),
      LWS_CB_REASON_MAPPING(RAW_CLOSE),
      LWS_CB_REASON_MAPPING(RAW_WRITEABLE),
      LWS_CB_REASON_MAPPING(RAW_ADOPT),
      LWS_CB_REASON_MAPPING(RAW_CONNECTED),
      LWS_CB_REASON_MAPPING(RAW_SKT_BIND_PROTOCOL),
      LWS_CB_REASON_MAPPING(RAW_SKT_DROP_PROTOCOL),
      LWS_CB_REASON_MAPPING(RAW_ADOPT_FILE),
      LWS_CB_REASON_MAPPING(RAW_RX_FILE),
      LWS_CB_REASON_MAPPING(RAW_WRITEABLE_FILE),
      LWS_CB_REASON_MAPPING(RAW_CLOSE_FILE),
      LWS_CB_REASON_MAPPING(RAW_FILE_BIND_PROTOCOL),
      LWS_CB_REASON_MAPPING(RAW_FILE_DROP_PROTOCOL),
      LWS_CB_REASON_MAPPING(TIMER),
      LWS_CB_REASON_MAPPING(EVENT_WAIT_CANCELLED),
      LWS_CB_REASON_MAPPING(CHILD_CLOSING),
      LWS_CB_REASON_MAPPING(CONNECTING),
      LWS_CB_REASON_MAPPING(VHOST_CERT_AGING),
      LWS_CB_REASON_MAPPING(VHOST_CERT_UPDATE),
      LWS_CB_REASON_MAPPING(MQTT_NEW_CLIENT_INSTANTIATED),
      LWS_CB_REASON_MAPPING(MQTT_IDLE),
      LWS_CB_REASON_MAPPING(MQTT_CLIENT_ESTABLISHED),
      LWS_CB_REASON_MAPPING(MQTT_SUBSCRIBED),
      LWS_CB_REASON_MAPPING(MQTT_CLIENT_WRITEABLE),
      LWS_CB_REASON_MAPPING(MQTT_CLIENT_RX),
      LWS_CB_REASON_MAPPING(MQTT_UNSUBSCRIBED),
      LWS_CB_REASON_MAPPING(MQTT_DROP_PROTOCOL),
      LWS_CB_REASON_MAPPING(MQTT_CLIENT_CLOSED),
      LWS_CB_REASON_MAPPING(MQTT_ACK),
      LWS_CB_REASON_MAPPING(MQTT_RESEND),
      LWS_CB_REASON_MAPPING(USER),
  };

  for (size_t i = 0; i < ARRAY_SIZE(lws_cb_reason_lut); ++i) {
    if (lws_cb_reason_lut[i].reason == reason) {
      return lws_cb_reason_lut[i].reason_txt;
    }
  }

  return "";
}

#else

const char* WebsocketLwsReasonToString(enum lws_callback_reasons reason) { return ""; }

#endif  // #if WEBSOCKET_DEBUG
